### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by jaroslavmraz** [leedave/Leeds-Flipper-Zero-Applications#34]
Hi, i have made larger command chain with 3s pause command. It has about 4mb. Then I had tried to make smaller 500comands chain. But it crash with memory problem. Is there a way how to use it like this? I wanted to simulate something like universal remote is doing. Maybe you can add option to ready file line by line not load all.

**Comment by jaroslavmraz** [comment]
I made some more tests but it crashed even with 10commands. And maybe be useful option for specify global delays. I had try to use it to switch channel on tv opens tv text and then open specific page there and it go too fast. Even with pause.

**Comment by leedave** [comment]
I'm not quite sure I understand what you're trying to do, but you are relating to Cross Remote right?. 4 MB or 500 Commands sound crazy. It's not a brute-force tool, you'd have to make something else if that's what you want. The focus is more on comfort, to easily automate every day tasks. 
I just tried chaining 10 pause commands of 9s together with a IR command, worked without problems. 
**Would be helpful for you if you could make longer pauses?** I think editing the maximum shouldn't be a big issue. 

I don't see refactoring the tool for reading line by line, as the tool is built to read out other files, store all in RAM and then write to it's own files. 

I also know that currently Flipper has an open since a few release issue on IR transmissions causing crashes. Quote below
 
`A huge (HVAC raw data) infrared remote load causes an Out-of-Memory crash. A fix is coming in the next release. Meanwhile, you can split your remotes into smaller files.`. 
Maybe what you're experiencing is in connection with this.

**Comment by Entr0p1a** [comment]
Hi, a new RC 0.95 was released which addresses the HVAC problem, would you please update the code to make the application compatible with the newest RC? 
Notably, I tried using the current version with the newer RC which gave an error of
Error
Preload failed
Infrared/xremote fap Update Application to use with this Firmware (ApiTooOld) 
May this be of help in troubleshooting.

**Comment by leedave** [comment]
@Entr0p1a 
The code is updated, so compilations with RC 0.95 now work. The new code is no longer here but in a new Repository (for a better overview of Apps)
[Flipper-Zero-Cross-Remote](https://github.com/leedave/flipper-zero-cross-remote)

The error you mention shows because the app was not compiled for your FW. Compiling will now work. If you do not compile you can use the mobile app, a site like flipc.org or simply get the .fap File I updated for you here
[Cross Remote, compiled for OFW](https://github.com/leedave/flipper-zero-cross-remote)
(let me know if you need a different FW version)
